cmake_minimum_required(VERSION 3.28)
project(cornobs-pressure-tests LANGUAGES C)
enable_testing()
add_executable(pressure-test pressure-test.c ../../frontend/utility/CornPressure.c)
target_compile_features(pressure-test PRIVATE c_std_11)
if(MSVC)
  target_compile_options(pressure-test PRIVATE /W4 /WX)
else()
  target_compile_options(pressure-test PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME gpu-pressure COMMAND pressure-test)
